### PR TITLE
adding in multiple cidr blocks and being allowed to set ports on serv…

### PR DESCRIPTION
**Pull request by brendangibat**
…ices and path proxy

Haha, I wasn't finished updating the previous PR.

This one adds in a few features to help out as well. I need to update the README first before a merge though. The existing functionality stays the same by default if no params are overriden.

### CODE REVIEW

**Comment by brendangibat** [comment]
Ah, oh yeah sorry about this - I did an automatic format. I can unset that if you want it back as it was.
It did however help find a missing semicolon on a return statement.

**Comment by JoelPM** [comment]
Formatting changes are fine with me. Let me know when you're ready for merge and I'll push the big green button :)

**Comment by brendangibat** [comment]
Alright I added what I wanted in the readme - should be better now, thanks!

**Comment by JoelPM** [comment]
LGTM, thanks again for the contributions.

**Pull request merged**
